### ISSUE TITLE
dataloader

### ISSUE THREAD

**Issue by hchoi71** [LetheSec/Adversarial_Training_Pytorch#1]
Thanks for well-organized code,

I found that for AT methods, you didn't do normalize input data, instead you do feed raw train/test data. Are there any reasons why?

# setup data loader
transform_train = transforms.Compose(
    [
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
    ]
)
transform_test = transforms.Compose(
    [
        transforms.ToTensor(),
    ]
)

**Comment by LetheSec** [comment]
I just followed the setup of most previous work. In fact, you can also normalize the input data in AT, you can refer to the code in this repository: https://github.com/P2333/Bag-of-Tricks-for-AT/blob/ebf1e9b56b79d8b8da71531ffe68f27fb1e59c44/train_cifar.py#L24

**Comment by hchoi71** [comment]
I see, thanks for checking :)
